import MenuComponent, { MenuListProps } from "@/components/menu/MenuComponent";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const menuList: MenuListProps[] = [
  {
    locationName: "Home",
    href: "/",
    key: "home",
  },
  {
    locationName: "Login",
    href: "/login",
    key: "login",
  },
  {
    locationName: "Join",
    href: "/join",
    key: "join",
  },
];

interface RootLayoutProps {
  children: React.ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <MenuComponent menuList={menuList}></MenuComponent>
        {children}
      </body>
    </html>
  );
}
